import express from "express";
import cors from "cors";

const app = express();
const PORT = 3001;

app.use(cors());

const TTL = 5 * 60 * 1000; // 5 minutes
const cache = {};

app.get("/", (req, res) => {
    res.json({ message: "KAI backend running" });
});

app.get("/api/word", async (req, res) => {
    const word = req.query.text;

    if (!word) {
        return res.status(400).json({
            error: "No word provided"
        });
    }

    const normalizedWord = word.toLowerCase().trim();
    const now = Date.now();

    // Cache check
    if (cache[normalizedWord]) {
        const { data, timestamp } = cache[normalizedWord];
        const elapsed = now - timestamp;

        if (elapsed < TTL) {
            console.log("Cache hit:", normalizedWord);
            return res.json(data);
        } else {
            console.log("Cache expired:", normalizedWord);
            delete cache[normalizedWord];
        }
    }

    console.log("Cache miss:", normalizedWord);

    try {
        const response = await fetch(
            `https://api.dictionaryapi.dev/api/v2/entries/en/${normalizedWord}`
        );

        if (!response.ok) {
            return res.status(404).json({
                error: "Word not found"
            });
        }

        const apiData = await response.json();

        const meaning =
            apiData[0]?.meanings[0]?.definitions[0]?.definition ||
            "Meaning not available";

        const example =
            apiData[0]?.meanings[0]?.definitions[0]?.example ||
            "Example not available";

        const result = {
            word: normalizedWord,
            meaning,
            etymology: "Etymology not available yet",
            analogy: "Analogy will be generated by AI later",
            example
        };

        cache[normalizedWord] = {
            data: result,
            timestamp: now
        };

        res.json(result);

    } catch (error) {
        console.error("Dictionary API error:", error);
        res.status(500).json({
            error: "Internal server error"
        });
    }
});

app.listen(PORT, () => {
    console.log(`KAI backend running on http://localhost:${PORT}`);
});